services:
  exoplanetes-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: exoplanetes-api
    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/exoplanetes_db
      SPRING_DATASOURCE_USERNAME: exoplanetes_user
      SPRING_DATASOURCE_PASSWORD: ${EXOPLANETES_DB_PASSWORD}

    networks:
      - backend
      - proxy

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.exoplanetes.rule=Host(`exoplanetes.gourouvin.dev`)"
      - "traefik.http.routers.exoplanetes.entrypoints=websecure"
      - "traefik.http.routers.exoplanetes.tls=true"
      - "traefik.http.routers.exoplanetes.tls.certresolver=letsencrypt"

      - "traefik.http.services.exoplanetes.loadbalancer.server.port=8080"

networks:
  backend:
    external: true
    name: vps-backend

  proxy:
    external: true
    name: vps-proxy