### Create exoplanete
POST http://localhost:8080/api/exoplanetes
Content-Type: application/json

{ "designation": "HD 189733 b", "masseTerre": 363.0, "distanceAl": 64.5, "observatoireId": 4 }


### Get exoplanete by id
GET http://localhost:8080/api/exoplanetes/1

### Get exoplantes
GET http://localhost:8080/api/exoplanetes

### Get exoplanete with queries params
GET http://localhost:8080/api/exoplanetes?observatoireId=2&page=0&size=1

### Patch exoplanete
PATCH http://localhost:8080/api/exoplanetes/1
Content-Type: application/json

{"designation": "TRAPPIST-1e"}