-- =====================================================================
-- V1 : Schema initial
-- Domaine : un OBSERVATOIRE decouvre plusieurs EXOPLANETES.
-- Relation : exoplanete N --- 1 observatoire (comme livre -> auteur).
-- =====================================================================

CREATE TABLE observatoire (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR(120) NOT NULL,
    pays        VARCHAR(80)  NOT NULL,
    altitude_m  INTEGER      NOT NULL,
    CONSTRAINT uq_observatoire_nom UNIQUE (nom)
);

CREATE TABLE exoplanete (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation      VARCHAR(80)   NOT NULL,
    masse_terre      NUMERIC(10,3) NOT NULL,   -- masse en masses terrestres (> 0)
    distance_al      NUMERIC(10,2) NOT NULL,   -- distance en annees-lumiere (> 0)
    statut           VARCHAR(20)   NOT NULL DEFAULT 'CANDIDATE',
    observatoire_id  BIGINT        NOT NULL,
    -- Colonne de verrouillage optimiste : mappee par @Version cote JPA.
    -- Hibernate l'incremente a chaque update et refuse un update dont la
    -- version ne correspond plus (OptimisticLockException). Sert au ticket
    -- "confirmer/rejeter" en cas de modifications concurrentes.
    version          BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT uq_exoplanete_designation UNIQUE (designation),
    CONSTRAINT fk_exoplanete_observatoire
        FOREIGN KEY (observatoire_id) REFERENCES observatoire (id),
    CONSTRAINT ck_exoplanete_statut
        CHECK (statut IN ('CANDIDATE', 'CONFIRMEE', 'REJETEE'))
);

-- Index sur la cle etrangere : utile pour le filtre ?observatoireId=...
-- (Postgres n'indexe PAS automatiquement les colonnes FK.)
CREATE INDEX idx_exoplanete_observatoire ON exoplanete (observatoire_id);
