-- =====================================================================
-- V2 : Jeu de donnees de test
-- On insere avec des id explicites (colonnes GENERATED BY DEFAULT le
-- permettent), puis on RESTART l'identite pour que les prochains INSERT
-- applicatifs ne rentrent pas en collision avec les id du seed.
-- =====================================================================

INSERT INTO observatoire (id, nom, pays, altitude_m) VALUES
    (1, 'Observatoire du Cerro Paranal', 'Chili',       2635),
    (2, 'Mauna Kea Observatory',         'Etats-Unis',  4207),
    (3, 'Roque de los Muchachos',        'Espagne',     2396),
    (4, 'Observatoire de Haute-Provence', 'France',      650);

INSERT INTO exoplanete (id, designation, masse_terre, distance_al, statut, observatoire_id, version) VALUES
    (1, 'Proxima Centauri b', 1.270,     4.24,  'CONFIRMEE', 1, 0),
    (2, 'TRAPPIST-1e',        0.692,    40.70,  'CONFIRMEE', 2, 0),
    (3, 'Kepler-442b',        2.360,  1206.00,  'CONFIRMEE', 2, 0),
    (4, 'Gliese 581g',        3.100,    20.40,  'REJETEE',   3, 0),
    (5, '51 Pegasi b',      150.000,    50.90,  'CONFIRMEE', 4, 0),
    (6, 'HD 209458 b',      219.000,   159.00,  'CONFIRMEE', 4, 0),
    (7, 'K2-18b',             8.630,   124.00,  'CANDIDATE', 3, 0),
    (8, 'TOI-700 d',          1.720,   101.40,  'CANDIDATE', 2, 0);

-- Repositionne les generateurs d'identite au-dessus des id deja utilises.
ALTER TABLE observatoire ALTER COLUMN id RESTART WITH 100;
ALTER TABLE exoplanete   ALTER COLUMN id RESTART WITH 100;
